---
    name: CI
    
    on:
      push:
        paths-ignore:
          - "**/README.md"
      pull_request:
        branches: [main]
        paths-ignore:
          - "**/README.md"
      schedule:
        - cron: "50 7 * * *"
    
    jobs:
      examples:
        name: Example | ${{ matrix.example.mcu }}-${{ matrix.example.env }}-${{ matrix.example.name }}
        runs-on: ubuntu-latest
        strategy:
          fail-fast: false
          matrix:
            example:
              - name: crispy-click-esp32c3_341706650098336338
                env: nostd
                mcu: esp32c3
              - name: esp-clock_357451677483992065
                env: std
                mcu: esp32c3
              - name: esp-gallery_348033994448699987
                env: nostd
                mcu: esp32c3
              - name: esp-keypad_346697192934736467
                env: nostd
                mcu: esp32s2
              - name: esp32-display_340062796817367636
                env: nostd
                mcu: esp32
              - name: esp32c3-display_340062891526849108
                env: nostd
                mcu: esp32c3
              - name: esp32s2-display_338804923638481490
                env: nostd
                mcu: esp32s2
        steps:
          - name: Checkout the repository
            uses: actions/checkout@v3
    
          - name: Pull Docker image (std)
            if: matrix.example.env == 'std'
            run: docker image pull wokwi/builder-rust-std-${{ matrix.example.mcu }}
    
          - name: Pull Docker image (no_std)
            if: matrix.example.env == 'no_std'
            run: docker image pull wokwi/builder-rust-nostd-esp
    
          - name: Test code example in Docker image (std)
            if: matrix.example.env == 'std'
            uses: addnab/docker-run-action@v3
            with:
              image: wokwi/builder-rust-std-${{ matrix.example.mcu }}
              options: -u esp -v ${{ github.workspace }}:/home/esp/workspace
              run: |
                export IDF_PATH=/home/esp/.espressif/frameworks/esp-idf-release-v4.4
                . /home/esp/export-esp.sh
                cat /home/esp/workspace/examples/${{ matrix.example.mcu }}-${{ matrix.example.env }}-${{ matrix.example.name }}/main.rs > rust-project/src/main.rs
                cd rust-project
                cargo build --release
    
          - name: Test code example in Docker image (no_std)
            if: matrix.example.env == 'no_std'
            uses: addnab/docker-run-action@v3
            with:
              image: wokwi/builder-rust-nostd-esp
              options: -u esp -v ${{ github.workspace }}:/home/esp/workspace
              run: |
                . /home/esp/export-esp.sh
                cat /home/esp/workspace/examples/${{ matrix.example.mcu }}-${{ matrix.example.env }}-${{ matrix.example.name }}/main.rs > rust-project-${{ matrix.example.mcu }}/src/main.rs
                cat /home/esp/workspace/examples/${{ matrix.example.mcu }}-${{ matrix.example.env }}-${{ matrix.example.name }}/Cargo.toml > rust-project-${{ matrix.example.mcu }}/Cargo.toml
                cd rust-project-${{ matrix.example.mcu }}
                cargo build --release